### ISSUE TITLE
Repo size

### ISSUE THREAD

**Issue by interrogator** [thiippal/gem-tools#7]
The models seem to be making the repository quite large.

I can think of three potential ways to minimise size. First, If there are many old model versions, maybe just wipe them: https://rtyley.github.io/bfg-repo-cleaner/

Second, there's GitHub's Large File Storage could help: https://git-lfs.github.com/

Finally, find a host for the data and have a `download_models()` method?

**Comment by thiippal** [comment]
Just checked this: must result from the fact that at one point, I had the entire corpus I compiled for my dissertation in the repo. I'll look into cleaning the repo ASAP.

**Comment by interrogator** [comment]
If that's the case, consider BFG!

**Comment by thiippal** [comment]
Working on this right now ... thanks for pointing this out!

**Comment by thiippal** [comment]
Cleaned up the repo using BFG; down from 195MB (yikes!) to 3.5MB!
