### ISSUE TITLE
GeM application on printed media 

### ISSUE THREAD

**Issue by ahlam2017** [thiippal/gem-tools#8]
I have a question? when I run my data on python and come up with the RST tree and LAYOUT tree. the tree is too big cant fit with the A4 page. what can I do to make the tree fitting page? shall I redraw it? or cut it? secondly, after having tree diagrams after the Run process is done, I don't get any statistics? for example how many elaboration relations? how many 16 Arial font type occur?How can I get the frequencies of the data? please Dr help me with that. here is I tagged a file to see how long is the tree.
![rst_graph heavenly escape](https://user-images.githubusercontent.com/78397789/106550135-7ed97600-654d-11eb-8a76-495c34c839dc.png). any suggestion is highly appreciated .

**Comment by thiippal** [comment]
Hi @ahlam2017, the tool is not intended to visualise such large documents. 

I suggest you either cut out the part of the visualisation you find useful, store the annotations for separate pages into separate XML files.

For querying the corpus, I suggest you learn a language such as XQuery.

**Comment by ahlam2017** [comment]
Dear Dr Tuomo,

Thank you so much for your kind reply . I will follow your recommended
software.

Respectfully yours.
