### ISSUE TITLE
test_images?

### ISSUE THREAD

**Issue by billy322** [thiippal/gem-tools#9]
Hi, 
Can you suggest where to find the file in test_images/  in "04_generate_gem.ipynb" thanks.

**Comment by thiippal** [comment]
Hi @billy322! I've just pushed the test image to the repository. Let me know if you encounter further problems!

**Comment by billy322** [comment]
Thanks for uploading the test image, however, I cannot run the "04_generate_gem.ipynb"
Particularly, I cannot run the line of code from "Draw the detected contours for examination" to the end, it said that " TypeError: 'module' object is not callable". Can you suggest how to tackle? Thanks.
